version: '3.8'
services:
  postgres-prisma-abstraction:
    container_name: postgres-prisma-abstraction
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '54321:5432'
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=1000'
      - '-c'
      - 'shared_buffers=128MB'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
